sweep:
  - device_train_microbatch_size: 32
    optimizer:
      name: adamw
      learning_rate: [1.0e-3, 1.0e-4]
      beta_0: 0.95 # [0.8, 0.9, 0.95]
      beta_1: 0.9
      eps: 1.0e-8
      decouple_weight_decay: false
      weight_decay: 0.1
      decay_norm_and_bias: true
      decay_embeddings: true
      metrics_log_interval: 100
    model: 
      block_loops: [1, 4, 8]